name: deploy
on:
  push:
    branches: [main]
    paths:
      - 'agent/**'
      - '.github/workflows/agent-deploy.yml'
  workflow_dispatch:
jobs:
  agent-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-agent:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: agent
          push: true
          cache-from: type=gha,scope=agent
          cache-to: type=gha,mode=max,scope=agent
          tags: ${{ env.DOCKER_IMAGE }}
  agent-run:
    needs: agent-deploy
    runs-on: ubuntu-latest
    env:
      NAME: clawk-agent
      VERSION: ${{ github.sha }}
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-agent:latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.YS_APPBOX_URL }}
          username: ${{ secrets.YS_APPBOX_USER }}
          key: ${{ secrets.YS_APPBOX_SSH_KEY }}
          port: ${{ secrets.YS_APPBOX_PORT }}
          envs: DOCKER_IMAGE,NAME,VERSION
          script: |
            set -e
            docker pull ${DOCKER_IMAGE}
            docker stop ${NAME} && docker rm ${NAME} || true
            docker run \
              --name ${NAME} \
              --detach \
              --restart on-failure \
              --volume /home/ec2-user/clawk-agent-workspace:/app/workspace \
              --env NAME=${NAME} \
              --env VERSION=${VERSION} \
              --env-file ~/.clawk-agent.vars \
              ${DOCKER_IMAGE}
